name: Emacs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["30.2", "30.1", "29.4", "29.1", "snapshot"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Check Emacs version
        run: emacs --version

      - name: Verify Config Load
        run: |
          # --batch: run without a UI
          # --debug-init: stop on errors
          # -l: load the file
          emacs --batch --debug-init \
          --load early-init.el \
          --load init.el \
          --load init.el.d/initial-packages.el \
          --load init.el.d/project-support-configs.el \
          --load init.el.d/language-specific-configs.el \
          --load init.el.d/user-interface-config.el \
          --load init.el.d/external-connections.el \
          --load init.el.d/user-functions.el

      - name: Byte-compile files
        run: |
          find . -name '*.el' -print0 | \
          xargs -0 emacs --batch -Q -f batch-byte-compile
